-- Auto-generated full privileges seed
-- Total: 137 privileges

INSERT INTO privileges (id, code, "nameEn", "nameAr", category, "requiresSpecialQualification", "isActive", "createdAt", "updatedAt") VALUES
('core-001', 'CORE-001', 'Comprehensive Oral Examination', 'الفحص الفموي الشامل', 'CORE', false, true, NOW(), NOW()),
('core-002', 'CORE-002', 'Dental Diagnosis and Treatment Planning', 'التشخيص وتخطيط العلاج السني', 'CORE', false, true, NOW(), NOW()),
('core-003', 'CORE-003', 'Local Anesthesia Administration', 'إعطاء التخدير الموضعي', 'CORE', false, true, NOW(), NOW()),
('core-004', 'CORE-004', 'Intraoral Radiograph Acquisition', 'التقاط الصور الشعاعية داخل الفم', 'CORE', false, true, NOW(), NOW()),
('core-005', 'CORE-005', 'Infection Control and Sterilization', 'مكافحة العدوى والتعقيم', 'CORE', false, true, NOW(), NOW()),
('core-006', 'CORE-006', 'Dental Emergency Management', 'إدارة حالات طوارئ الأسنان', 'CORE', false, true, NOW(), NOW()),
('core-007', 'CORE-007', 'Medical Emergency Response', 'الاستجابة للطوارئ الطبية', 'CORE', false, true, NOW(), NOW()),
('core-008', 'CORE-008', 'Patient Health History Assessment', 'تقييم التاريخ الصحي للمريض', 'CORE', false, true, NOW(), NOW()),
('core-009', 'CORE-009', 'Prophylaxis and Oral Hygiene Instructions', 'التنظيف الوقائي وتعليمات نظافة الفم', 'CORE', false, true, NOW(), NOW()),
('core-010', 'CORE-010', 'Prescription of Dental Medications', 'وصف الأدوية السنية', 'CORE', false, true, NOW(), NOW()),
('rest-001', 'REST-001', 'Amalgam Restoration - Simple', 'حشوة الأملغم - بسيطة', 'RESTORATIVE', false, true, NOW(), NOW()),
('rest-002', 'REST-002', 'Amalgam Restoration - Complex', 'حشوة الأملغم - معقدة', 'RESTORATIVE', false, true, NOW(), NOW()),
('rest-003', 'REST-003', 'Composite Restoration - Anterior', 'حشوة الكمبوزيت - أمامية', 'RESTORATIVE', false, true, NOW(), NOW()),
('rest-004', 'REST-004', 'Composite Restoration - Posterior', 'حشوة الكمبوزيت - خلفية', 'RESTORATIVE', false, true, NOW(), NOW()),
('rest-005', 'REST-005', 'Glass Ionomer Restoration', 'حشوة الزجاج الأيونومري', 'RESTORATIVE', false, true, NOW(), NOW()),
('rest-006', 'REST-006', 'Temporary Restoration', 'الحشوة المؤقتة', 'RESTORATIVE', false, true, NOW(), NOW()),
('rest-007', 'REST-007', 'Cavity Preparation', 'تحضير التجويف', 'RESTORATIVE', false, true, NOW(), NOW()),
('rest-008', 'REST-008', 'Matrix Band Placement', 'وضع شريط المصفوفة', 'RESTORATIVE', false, true, NOW(), NOW()),
('rest-009', 'REST-009', 'Pulp Capping - Direct', 'تغطية اللب - مباشرة', 'RESTORATIVE', false, true, NOW(), NOW()),
('rest-010', 'REST-010', 'Pulp Capping - Indirect', 'تغطية اللب - غير مباشرة', 'RESTORATIVE', false, true, NOW(), NOW()),
('rest-011', 'REST-011', 'Core Buildup', 'بناء اللب', 'RESTORATIVE', false, true, NOW(), NOW()),
('rest-012', 'REST-012', 'Post and Core Placement', 'وضع الدعامة والبناء', 'RESTORATIVE', false, true, NOW(), NOW()),
('rest-013', 'REST-013', 'Dental Bonding Procedures', 'إجراءات الربط السني', 'RESTORATIVE', false, true, NOW(), NOW()),
('rest-014', 'REST-014', 'Tooth Desensitization', 'إزالة حساسية الأسنان', 'RESTORATIVE', false, true, NOW(), NOW()),
('rest-015', 'REST-015', 'Dental Veneer Placement', 'وضع قشور الأسنان', 'RESTORATIVE', false, true, NOW(), NOW()),
('pedo-001', 'PEDO-001', 'Pediatric Behavior Management', 'إدارة سلوك الأطفال', 'PEDIATRIC', false, true, NOW(), NOW()),
('pedo-002', 'PEDO-002', 'Pulpotomy - Primary Teeth', 'بتر اللب - الأسنان اللبنية', 'PEDIATRIC', false, true, NOW(), NOW()),
('pedo-003', 'PEDO-003', 'Pulpectomy - Primary Teeth', 'استئصال اللب - الأسنان اللبنية', 'PEDIATRIC', false, true, NOW(), NOW()),
('pedo-004', 'PEDO-004', 'Stainless Steel Crown Placement', 'وضع تاج الفولاذ المقاوم للصدأ', 'PEDIATRIC', false, true, NOW(), NOW()),
('pedo-005', 'PEDO-005', 'Space Maintainer Placement', 'وضع حافظ المسافة', 'PEDIATRIC', false, true, NOW(), NOW()),
('pedo-006', 'PEDO-006', 'Topical Fluoride Application', 'تطبيق الفلورايد الموضعي', 'PEDIATRIC', false, true, NOW(), NOW()),
('pedo-007', 'PEDO-007', 'Pit and Fissure Sealant Application', 'تطبيق مانع التسوس للشقوق', 'PEDIATRIC', false, true, NOW(), NOW()),
('pedo-008', 'PEDO-008', 'Pediatric Extraction - Primary Teeth', 'خلع الأسنان اللبنية', 'PEDIATRIC', false, true, NOW(), NOW()),
('pedo-009', 'PEDO-009', 'Pediatric Strip Crown', 'تاج شريطي للأطفال', 'PEDIATRIC', false, true, NOW(), NOW()),
('pedo-010', 'PEDO-010', 'Silver Diamine Fluoride Application', 'تطبيق فلورايد الفضة الثنائي الأمين', 'PEDIATRIC', false, true, NOW(), NOW()),
('pedo-011', 'PEDO-011', 'Pediatric Sedation Management', 'إدارة التخدير للأطفال', 'PEDIATRIC', true, true, NOW(), NOW()),
('pedo-012', 'PEDO-012', 'Interceptive Orthodontic Treatment', 'العلاج التقويمي الاعتراضي', 'PEDIATRIC', false, true, NOW(), NOW()),
('ortho-001', 'ORTHO-001', 'Orthodontic Diagnosis and Treatment Planning', 'تشخيص وتخطيط علاج تقويم الأسنان', 'ORTHODONTIC', true, true, NOW(), NOW()),
('ortho-002', 'ORTHO-002', 'Cephalometric Analysis', 'التحليل السيفالومتري', 'ORTHODONTIC', true, true, NOW(), NOW()),
('ortho-003', 'ORTHO-003', 'Fixed Orthodontic Appliance Placement', 'وضع جهاز تقويم الأسنان الثابت', 'ORTHODONTIC', true, true, NOW(), NOW()),
('ortho-004', 'ORTHO-004', 'Removable Orthodontic Appliance', 'جهاز تقويم الأسنان المتحرك', 'ORTHODONTIC', true, true, NOW(), NOW()),
('ortho-005', 'ORTHO-005', 'Orthodontic Retainer Fabrication', 'تصنيع مثبت تقويم الأسنان', 'ORTHODONTIC', true, true, NOW(), NOW()),
('ortho-006', 'ORTHO-006', 'Bracket Bonding and Debonding', 'ربط وفك ربط الحاصرات', 'ORTHODONTIC', true, true, NOW(), NOW()),
('ortho-007', 'ORTHO-007', 'Arch Wire Placement and Adjustment', 'وضع وتعديل السلك القوسي', 'ORTHODONTIC', true, true, NOW(), NOW()),
('ortho-008', 'ORTHO-008', 'Orthodontic Band Placement', 'وضع أحزمة تقويم الأسنان', 'ORTHODONTIC', true, true, NOW(), NOW()),
('ortho-009', 'ORTHO-009', 'Clear Aligner Therapy', 'علاج المقومات الشفافة', 'ORTHODONTIC', true, true, NOW(), NOW()),
('ortho-010', 'ORTHO-010', 'Functional Appliance Therapy', 'العلاج بالأجهزة الوظيفية', 'ORTHODONTIC', true, true, NOW(), NOW()),
('ortho-011', 'ORTHO-011', 'Palatal Expansion Appliance', 'جهاز توسيع الحنك', 'ORTHODONTIC', true, true, NOW(), NOW()),
('ortho-012', 'ORTHO-012', 'Temporary Anchorage Device Placement', 'وضع أجهزة التثبيت المؤقتة', 'ORTHODONTIC', true, true, NOW(), NOW()),
('ortho-013', 'ORTHO-013', 'Orthodontic Emergency Management', 'إدارة طوارئ تقويم الأسنان', 'ORTHODONTIC', false, true, NOW(), NOW()),
('ortho-014', 'ORTHO-014', 'Lingual Orthodontic Appliance', 'جهاز تقويم الأسنان اللساني', 'ORTHODONTIC', true, true, NOW(), NOW()),
('ortho-015', 'ORTHO-015', 'Orthodontic Interproximal Reduction', 'التخفيض البيني لتقويم الأسنان', 'ORTHODONTIC', true, true, NOW(), NOW()),
('pros-001', 'PROS-001', 'Complete Denture - Maxillary', 'طقم أسنان كامل - علوي', 'PROSTHODONTIC', false, true, NOW(), NOW()),
('pros-002', 'PROS-002', 'Complete Denture - Mandibular', 'طقم أسنان كامل - سفلي', 'PROSTHODONTIC', false, true, NOW(), NOW()),
('pros-003', 'PROS-003', 'Removable Partial Denture - Acrylic', 'طقم أسنان جزئي متحرك - أكريليك', 'PROSTHODONTIC', false, true, NOW(), NOW()),
('pros-004', 'PROS-004', 'Removable Partial Denture - Metal Framework', 'طقم أسنان جزئي متحرك - إطار معدني', 'PROSTHODONTIC', false, true, NOW(), NOW()),
('pros-005', 'PROS-005', 'Crown Preparation - Full Coverage', 'تحضير التاج - تغطية كاملة', 'PROSTHODONTIC', false, true, NOW(), NOW()),
('pros-006', 'PROS-006', 'Crown Cementation', 'تثبيت التاج', 'PROSTHODONTIC', false, true, NOW(), NOW()),
('pros-007', 'PROS-007', 'Fixed Bridge Preparation', 'تحضير الجسر الثابت', 'PROSTHODONTIC', false, true, NOW(), NOW()),
('pros-008', 'PROS-008', 'Fixed Bridge Cementation', 'تثبيت الجسر الثابت', 'PROSTHODONTIC', false, true, NOW(), NOW()),
('pros-009', 'PROS-009', 'Implant Prosthodontics - Single Crown', 'تركيبات الزراعة - تاج واحد', 'PROSTHODONTIC', true, true, NOW(), NOW()),
('pros-010', 'PROS-010', 'Implant Prosthodontics - Fixed Bridge', 'تركيبات الزراعة - جسر ثابت', 'PROSTHODONTIC', true, true, NOW(), NOW()),
('pros-011', 'PROS-011', 'Implant Overdenture', 'طقم أسنان مدعوم بالزراعة', 'PROSTHODONTIC', true, true, NOW(), NOW()),
('pros-012', 'PROS-012', 'Temporary Crown Fabrication', 'تصنيع التاج المؤقت', 'PROSTHODONTIC', false, true, NOW(), NOW()),
('pros-013', 'PROS-013', 'Temporary Bridge Fabrication', 'تصنيع الجسر المؤقت', 'PROSTHODONTIC', false, true, NOW(), NOW()),
('pros-014', 'PROS-014', 'Porcelain Laminate Veneer', 'قشور البورسلين', 'PROSTHODONTIC', false, true, NOW(), NOW()),
('pros-015', 'PROS-015', 'Inlay/Onlay Preparation', 'تحضير الحشوات الداخلية/الخارجية', 'PROSTHODONTIC', false, true, NOW(), NOW()),
('pros-016', 'PROS-016', 'Denture Reline - Direct', 'إعادة تبطين طقم الأسنان - مباشر', 'PROSTHODONTIC', false, true, NOW(), NOW()),
('pros-017', 'PROS-017', 'Denture Repair', 'إصلاح طقم الأسنان', 'PROSTHODONTIC', false, true, NOW(), NOW()),
('pros-018', 'PROS-018', 'Occlusal Adjustment', 'تعديل الإطباق', 'PROSTHODONTIC', false, true, NOW(), NOW()),
('pros-019', 'PROS-019', 'Maxillofacial Prosthesis', 'التعويضات الوجهية الفكية', 'PROSTHODONTIC', true, true, NOW(), NOW()),
('pros-020', 'PROS-020', 'CAD/CAM Crown Fabrication', 'تصنيع التاج بالحاسب الآلي', 'PROSTHODONTIC', false, true, NOW(), NOW()),
('perio-001', 'PERIO-001', 'Scaling and Root Planing - Localized', 'تقليح الجذور - موضعي', 'PERIODONTIC', false, true, NOW(), NOW()),
('perio-002', 'PERIO-002', 'Scaling and Root Planing - Full Mouth', 'تقليح الجذور - الفم الكامل', 'PERIODONTIC', false, true, NOW(), NOW()),
('perio-003', 'PERIO-003', 'Periodontal Maintenance', 'صيانة اللثة', 'PERIODONTIC', false, true, NOW(), NOW()),
('perio-004', 'PERIO-004', 'Gingivectomy', 'استئصال اللثة', 'PERIODONTIC', true, true, NOW(), NOW()),
('perio-005', 'PERIO-005', 'Gingivoplasty', 'تشكيل اللثة', 'PERIODONTIC', true, true, NOW(), NOW()),
('perio-006', 'PERIO-006', 'Crown Lengthening', 'إطالة التاج السريري', 'PERIODONTIC', true, true, NOW(), NOW()),
('perio-007', 'PERIO-007', 'Periodontal Flap Surgery', 'جراحة السديلة اللثوية', 'PERIODONTIC', true, true, NOW(), NOW()),
('perio-008', 'PERIO-008', 'Bone Grafting - Periodontal', 'ترقيع العظم - لثوي', 'PERIODONTIC', true, true, NOW(), NOW()),
('perio-009', 'PERIO-009', 'Guided Tissue Regeneration', 'تجديد الأنسجة الموجه', 'PERIODONTIC', true, true, NOW(), NOW()),
('perio-010', 'PERIO-010', 'Soft Tissue Graft', 'ترقيع الأنسجة الرخوة', 'PERIODONTIC', true, true, NOW(), NOW()),
('perio-011', 'PERIO-011', 'Frenectomy', 'قطع اللجام', 'PERIODONTIC', false, true, NOW(), NOW()),
('perio-012', 'PERIO-012', 'Periodontal Splinting', 'تجبير اللثة', 'PERIODONTIC', false, true, NOW(), NOW()),
('perio-013', 'PERIO-013', 'Local Antimicrobial Delivery', 'توصيل مضادات الميكروبات الموضعية', 'PERIODONTIC', false, true, NOW(), NOW()),
('perio-014', 'PERIO-014', 'Dental Implant Placement', 'زراعة الأسنان', 'PERIODONTIC', true, true, NOW(), NOW()),
('perio-015', 'PERIO-015', 'Peri-implantitis Treatment', 'علاج التهاب حول الزراعة', 'PERIODONTIC', true, true, NOW(), NOW()),
('surg-001', 'SURG-001', 'Simple Extraction - Anterior', 'خلع بسيط - أمامي', 'ORAL_SURGERY', false, true, NOW(), NOW()),
('surg-002', 'SURG-002', 'Simple Extraction - Posterior', 'خلع بسيط - خلفي', 'ORAL_SURGERY', false, true, NOW(), NOW()),
('surg-003', 'SURG-003', 'Surgical Extraction', 'خلع جراحي', 'ORAL_SURGERY', false, true, NOW(), NOW()),
('surg-004', 'SURG-004', 'Impacted Tooth Removal - Soft Tissue', 'إزالة السن المنطمر - الأنسجة الرخوة', 'ORAL_SURGERY', false, true, NOW(), NOW()),
('surg-005', 'SURG-005', 'Impacted Tooth Removal - Partial Bony', 'إزالة السن المنطمر - عظمي جزئي', 'ORAL_SURGERY', true, true, NOW(), NOW()),
('surg-006', 'SURG-006', 'Impacted Tooth Removal - Full Bony', 'إزالة السن المنطمر - عظمي كامل', 'ORAL_SURGERY', true, true, NOW(), NOW()),
('surg-007', 'SURG-007', 'Third Molar Extraction', 'خلع ضرس العقل', 'ORAL_SURGERY', false, true, NOW(), NOW()),
('surg-008', 'SURG-008', 'Incision and Drainage', 'شق وتصريف', 'ORAL_SURGERY', false, true, NOW(), NOW()),
('surg-009', 'SURG-009', 'Biopsy - Soft Tissue', 'خزعة - الأنسجة الرخوة', 'ORAL_SURGERY', false, true, NOW(), NOW()),
('surg-010', 'SURG-010', 'Biopsy - Hard Tissue', 'خزعة - الأنسجة الصلبة', 'ORAL_SURGERY', true, true, NOW(), NOW()),
('surg-011', 'SURG-011', 'Suturing', 'الخياطة', 'ORAL_SURGERY', false, true, NOW(), NOW()),
('surg-012', 'SURG-012', 'Alveoloplasty', 'تشكيل العظم السنخي', 'ORAL_SURGERY', false, true, NOW(), NOW()),
('surg-013', 'SURG-013', 'Operculectomy', 'استئصال الغطاء اللثوي', 'ORAL_SURGERY', false, true, NOW(), NOW()),
('surg-014', 'SURG-014', 'Tooth Reimplantation', 'إعادة زراعة السن', 'ORAL_SURGERY', false, true, NOW(), NOW()),
('surg-015', 'SURG-015', 'Surgical Exposure of Tooth', 'كشف السن جراحياً', 'ORAL_SURGERY', true, true, NOW(), NOW()),
('surg-016', 'SURG-016', 'Cyst Enucleation', 'استئصال الكيس', 'ORAL_SURGERY', true, true, NOW(), NOW()),
('surg-017', 'SURG-017', 'Torus Removal', 'إزالة النتوء العظمي', 'ORAL_SURGERY', true, true, NOW(), NOW()),
('surg-018', 'SURG-018', 'Bone Grafting - Pre-implant', 'ترقيع العظم - ما قبل الزراعة', 'ORAL_SURGERY', true, true, NOW(), NOW()),
('surg-019', 'SURG-019', 'Sinus Lift Procedure', 'رفع الجيب الأنفي', 'ORAL_SURGERY', true, true, NOW(), NOW()),
('surg-020', 'SURG-020', 'IV Sedation Administration', 'إعطاء التخدير الوريدي', 'ORAL_SURGERY', true, true, NOW(), NOW()),
('endo-001', 'ENDO-001', 'Pulp Vitality Testing', 'اختبار حيوية اللب', 'ENDODONTIC', false, true, NOW(), NOW()),
('endo-002', 'ENDO-002', 'Pulpectomy - Permanent Teeth', 'استئصال اللب - الأسنان الدائمة', 'ENDODONTIC', false, true, NOW(), NOW()),
('endo-003', 'ENDO-003', 'Root Canal Treatment - Anterior', 'علاج قناة الجذر - أمامي', 'ENDODONTIC', false, true, NOW(), NOW()),
('endo-004', 'ENDO-004', 'Root Canal Treatment - Premolar', 'علاج قناة الجذر - ضواحك', 'ENDODONTIC', false, true, NOW(), NOW()),
('endo-005', 'ENDO-005', 'Root Canal Treatment - Molar', 'علاج قناة الجذر - ضرس', 'ENDODONTIC', false, true, NOW(), NOW()),
('endo-006', 'ENDO-006', 'Root Canal Retreatment', 'إعادة علاج قناة الجذر', 'ENDODONTIC', true, true, NOW(), NOW()),
('endo-007', 'ENDO-007', 'Apicoectomy', 'قطع قمة الجذر', 'ENDODONTIC', true, true, NOW(), NOW()),
('endo-008', 'ENDO-008', 'Internal Bleaching', 'التبييض الداخلي', 'ENDODONTIC', false, true, NOW(), NOW()),
('endo-009', 'ENDO-009', 'Perforation Repair', 'إصلاح الثقب', 'ENDODONTIC', true, true, NOW(), NOW()),
('endo-010', 'ENDO-010', 'Apexification', 'تكوين قمة الجذر', 'ENDODONTIC', true, true, NOW(), NOW()),
('endo-011', 'ENDO-011', 'Regenerative Endodontics', 'علاج اللب التجديدي', 'ENDODONTIC', true, true, NOW(), NOW()),
('endo-012', 'ENDO-012', 'Emergency Endodontic Treatment', 'علاج اللب الطارئ', 'ENDODONTIC', false, true, NOW(), NOW()),
('med-001', 'MED-001', 'Oral Lesion Diagnosis', 'تشخيص آفات الفم', 'ORAL_MEDICINE', false, true, NOW(), NOW()),
('med-002', 'MED-002', 'TMJ Evaluation and Management', 'تقييم وإدارة مفصل الفك', 'ORAL_MEDICINE', false, true, NOW(), NOW()),
('med-003', 'MED-003', 'Oral Cancer Screening', 'فحص سرطان الفم', 'ORAL_MEDICINE', false, true, NOW(), NOW()),
('med-004', 'MED-004', 'Salivary Gland Disorder Management', 'إدارة اضطرابات الغدد اللعابية', 'ORAL_MEDICINE', false, true, NOW(), NOW()),
('med-005', 'MED-005', 'Orofacial Pain Management', 'إدارة آلام الوجه والفكين', 'ORAL_MEDICINE', false, true, NOW(), NOW()),
('med-006', 'MED-006', 'Occlusal Splint Therapy', 'العلاج بجبيرة الإطباق', 'ORAL_MEDICINE', false, true, NOW(), NOW()),
('med-007', 'MED-007', 'Burning Mouth Syndrome Management', 'إدارة متلازمة الفم الحارق', 'ORAL_MEDICINE', false, true, NOW(), NOW()),
('med-008', 'MED-008', 'Xerostomia Management', 'إدارة جفاف الفم', 'ORAL_MEDICINE', false, true, NOW(), NOW()),
('med-009', 'MED-009', 'Oral Lichen Planus Management', 'إدارة الحزاز المسطح الفموي', 'ORAL_MEDICINE', false, true, NOW(), NOW()),
('med-010', 'MED-010', 'Recurrent Aphthous Ulcer Management', 'إدارة القرح القلاعية المتكررة', 'ORAL_MEDICINE', false, true, NOW(), NOW()),
('rad-001', 'RAD-001', 'Periapical Radiograph Interpretation', 'تفسير الأشعة حول قمة الجذر', 'DIAGNOSTIC', false, true, NOW(), NOW()),
('rad-002', 'RAD-002', 'Bitewing Radiograph Interpretation', 'تفسير أشعة العض الجناحية', 'DIAGNOSTIC', false, true, NOW(), NOW()),
('rad-003', 'RAD-003', 'Panoramic Radiograph Acquisition', 'التقاط الأشعة البانورامية', 'DIAGNOSTIC', false, true, NOW(), NOW()),
('rad-004', 'RAD-004', 'Panoramic Radiograph Interpretation', 'تفسير الأشعة البانورامية', 'DIAGNOSTIC', false, true, NOW(), NOW()),
('rad-005', 'RAD-005', 'Cephalometric Radiograph Acquisition', 'التقاط الأشعة السيفالومترية', 'DIAGNOSTIC', false, true, NOW(), NOW()),
('rad-006', 'RAD-006', 'CBCT Acquisition', 'التقاط التصوير المقطعي المخروطي', 'DIAGNOSTIC', true, true, NOW(), NOW()),
('rad-007', 'RAD-007', 'CBCT Interpretation', 'تفسير التصوير المقطعي المخروطي', 'DIAGNOSTIC', true, true, NOW(), NOW()),
('rad-008', 'RAD-008', 'Occlusal Radiograph Interpretation', 'تفسير الأشعة الإطباقية', 'DIAGNOSTIC', false, true, NOW(), NOW())
ON CONFLICT (id) DO UPDATE SET
  code = EXCLUDED.code,
  "nameEn" = EXCLUDED."nameEn",
  "nameAr" = EXCLUDED."nameAr",
  category = EXCLUDED.category,
  "requiresSpecialQualification" = EXCLUDED."requiresSpecialQualification",
  "updatedAt" = NOW();
